name: Scrape ÖMAG Market Prices

on:
  schedule:
    # Triggers every day at 16:00 UTC
    - cron: '0 16 * * *'
  workflow_dispatch: # Allows you to trigger this workflow manually anytime for testing

jobs:
  scrape-and-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Run Scraper Script
        env:
          GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
        run: node scripts/scraper.js